package org.classtrim.plugin;

import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Label;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.Tag;
import org.junit.jupiter.api.Assertions;

import java.util.ArrayList;
import java.util.List;

/**
 * Property-based test for the tool-window publication state machine that
 * backs {@link ClassTrimToolWindowPanel#updateSuggestions}'s success /
 * failure / cancellation transitions.
 *
 * <p>Validates: Requirements 4.4, 5.1, 5.5 — the "Tool-window publication
 * state machine" property from the {@code idea-plugin} design (Correctness
 * Property 5).</p>
 *
 * <p>The system under test is a small <em>model publication</em> that
 * mirrors the publication semantics observed by
 * {@link ClassTrimToolWindowPanel}: only a {@code Success(L)} replaces the
 * published list; {@code Failure} and {@code Cancellation} leave the
 * published list unchanged. The model is deliberately separate from
 * {@link ClassTrimToolWindowPanel} because the production panel pulls in
 * the IntelliJ Platform and Swing on the EDT; lifting only the
 * publication-state logic into a tiny model lets the property exercise the
 * full random-event state machine without any IntelliJ runtime on the
 * classpath.</p>
 *
 * <p>The property generates random sequences of {@code SUCCESS(L) |
 * FAILURE | CANCELLATION} events of length 0–32 (50/25/25 weighted, per
 * the design's "Test Data and Generators" section) and applies them in
 * order to a single {@link ModelPublication}. After every prefix it
 * cross-checks the observed published list against an oracle: the most
 * recent {@code SUCCESS}'s list if any has occurred, otherwise the initial
 * empty list.</p>
 */
class PublicationStateMachinePropertyTest {

    /**
     * Minimal model of {@link ClassTrimToolWindowPanel}'s publication
     * semantics.
     *
     * <p>{@link #onSuccess(List)} mirrors the body of
     * {@link ClassTrimToolWindowPanel#updateSuggestions}: it replaces the
     * published list with a defensive copy of the supplied suggestions.
     * {@link #onFailure()} and {@link #onCancellation()} are no-ops,
     * matching R5.5 ("failure / cancellation paths must never call
     * updateSuggestions"). {@link #published()} returns the same state
     * observed by clients of the tool window.</p>
     *
     * <p>{@code Object} is used in place of
     * {@code RefactoringSuggestion} because the production type lives in
     * {@code classtrim-core} and pulling it in would expand the test
     * dependency graph for no semantic benefit; the publication state
     * machine treats the list opaquely. Plain {@link String} values are
     * generated by the property below.</p>
     */
    static final class ModelPublication {
        private List<Object> published = List.of();

        void onSuccess(List<Object> suggestions) {
            published = List.copyOf(suggestions);
        }

        void onFailure() {
            // No-op: failure must not replace the published list (R5.5).
        }

        void onCancellation() {
            // No-op: cancellation must not replace the published list (R4.4, R5.5).
        }

        List<Object> published() {
            return published;
        }
    }

    /**
     * Event alphabet for the schedule generator. Mirrors the three
     * publication transitions observed by
     * {@link ClassTrimToolWindowPanel}: {@code SUCCESS} carries a list of
     * suggestions; {@code FAILURE} and {@code CANCELLATION} carry no
     * payload.
     */
    enum EventType { SUCCESS, FAILURE, CANCELLATION }

    /** A single timeline event paired with its (possibly empty) payload. */
    static final class Event {
        final EventType type;
        final List<Object> payload; // non-null for SUCCESS, empty for others

        Event(EventType type, List<Object> payload) {
            this.type = type;
            this.payload = payload;
        }

        @Override
        public String toString() {
            return type == EventType.SUCCESS
                    ? "SUCCESS(" + payload + ")"
                    : type.name();
        }
    }

    /**
     * <strong>Feature: idea-plugin, Property 5: Tool-window publication
     * state machine.</strong>
     *
     * <p>For any random schedule of {@code SUCCESS(L) | FAILURE |
     * CANCELLATION} events (length 0–32) submitted to a
     * {@link ModelPublication}, after every prefix the published list
     * equals the most recent {@code SUCCESS}'s list if any
     * {@code SUCCESS} has occurred, otherwise the initial empty list.</p>
     *
     * <p>Validates: Requirements 4.4, 5.1, 5.5.</p>
     */
    @Property(tries = 100)
    // The human-readable label per the design ("Feature: idea-plugin,
    // Property 5: ...") is published via @Label below. JUnit 5's @Tag does
    // not accept colons or commas, so a sanitized identifier is used here
    // for tooling-level filtering.
    @Tag("idea-plugin-property-5")
    @Label("Feature: idea-plugin, Property 5: Tool-window publication state machine")
    void publicationStateMachineMatchesMostRecentSuccess(
            @ForAll("eventSchedules") List<Event> schedule) {

        ModelPublication panel = new ModelPublication();

        // Pre-condition: a freshly constructed model panel publishes the
        // empty list. This anchors the prefix-invariant at index 0.
        Assertions.assertEquals(List.of(), panel.published(),
                "ModelPublication must start with an empty published list");

        // Oracle: the expected published list is the most recent SUCCESS
        // payload if any has occurred, otherwise the initial empty list.
        List<Object> expectedPublished = List.of();

        for (int i = 0; i < schedule.size(); i++) {
            final int idx = i;
            final Event event = schedule.get(i);

            switch (event.type) {
                case SUCCESS -> {
                    panel.onSuccess(event.payload);
                    // Replace the oracle's expected published list with a
                    // defensive copy, mirroring ModelPublication.onSuccess.
                    expectedPublished = List.copyOf(event.payload);
                }
                case FAILURE -> {
                    panel.onFailure();
                    // expectedPublished unchanged (R5.5).
                }
                case CANCELLATION -> {
                    panel.onCancellation();
                    // expectedPublished unchanged (R4.4, R5.5).
                }
            }

            // Prefix invariant: after every event, the published list
            // equals the most recent SUCCESS's payload (or the initial
            // empty list if none has occurred yet).
            final List<Object> expectedAtIdx = expectedPublished;
            Assertions.assertEquals(expectedAtIdx, panel.published(),
                    () -> "Observed published list diverged from oracle after event "
                            + event + " at index " + idx
                            + " (prefix=" + schedule.subList(0, idx + 1) + ")");
        }
    }

    // --- Generators -----------------------------------------------------------

    /**
     * Schedule generator: list of length 0–32 where each event is drawn
     * from the weighted alphabet {@code SUCCESS:50, FAILURE:25,
     * CANCELLATION:25}, per the design's "Test Data and Generators"
     * section. {@code SUCCESS} events carry a list of size 0–8 of plain
     * {@link String} payloads (standing in for
     * {@code RefactoringSuggestion} to avoid pulling in heavy
     * dependencies, since the publication state machine treats the list
     * opaquely).
     */
    @Provide
    Arbitrary<List<Event>> eventSchedules() {
        Arbitrary<List<Object>> successPayloads = Arbitraries.strings()
                .alpha().numeric().ofMinLength(0).ofMaxLength(16)
                .map(s -> (Object) s)
                .list().ofMinSize(0).ofMaxSize(8);

        Arbitrary<Event> successEvents = successPayloads
                .map(payload -> new Event(EventType.SUCCESS, new ArrayList<>(payload)));

        Arbitrary<Event> failureEvents = Arbitraries.just(
                new Event(EventType.FAILURE, List.of()));

        Arbitrary<Event> cancellationEvents = Arbitraries.just(
                new Event(EventType.CANCELLATION, List.of()));

        // Weighted draw: SUCCESS:50, FAILURE:25, CANCELLATION:25 (matches
        // the design's "Test Data and Generators" section).
        // The explicit <Event> type witness is required so that
        // Arbitraries.frequencyOf can unify the three Arbitrary<Event>
        // branches into Arbitrary<? extends Event>.
        Arbitrary<Event> events = Arbitraries.<Event>frequencyOf(
                net.jqwik.api.Tuple.of(50, successEvents),
                net.jqwik.api.Tuple.of(25, failureEvents),
                net.jqwik.api.Tuple.of(25, cancellationEvents));

        return events.list().ofMinSize(0).ofMaxSize(32);
    }
}
